ALTER TABLE `quest_template`
ADD COLUMN `RewSkillLineId` int(11) unsigned NOT NULL DEFAULT '0' AFTER `OfferRewardEmoteDelay4`,
ADD COLUMN `RewSkillPoints` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewSkillLineId`,
ADD COLUMN                                   `RewRepMask` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewSkillPoints`,
ADD COLUMN                                   `QuestGiverPortrait` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewRepMask`,
ADD COLUMN                                   `QuestTurnInPortrait` int(11) unsigned NOT NULL DEFAULT '0' AFTER `QuestGiverPortrait`,
ADD COLUMN                                   `RewCurrencyId1` int(11) unsigned NOT NULL DEFAULT '0' AFTER `QuestTurnInPortrait`,
ADD COLUMN                                   `RewCurrencyCount1` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyId1`,
ADD COLUMN                                   `RewCurrencyId2` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyCount1`,
ADD COLUMN                                   `RewCurrencyCount2` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyId2`,
ADD COLUMN                                   `RewCurrencyId3` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyCount2`,
ADD COLUMN                                   `RewCurrencyCount3` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyId3`,
ADD COLUMN                                   `RewCurrencyId4` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyCount3`,
ADD COLUMN                                   `RewCurrencyCount4` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyId4`,
ADD COLUMN                                   `ReqCurrencyId1` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyCount4`,
ADD COLUMN                                   `ReqCurrencyCount1` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyId1`,
ADD COLUMN                                   `ReqCurrencyId2` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyCount1`,
ADD COLUMN                                   `ReqCurrencyCount2` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyId2`,
ADD COLUMN                                   `ReqCurrencyId3` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyCount2`,
ADD COLUMN                                   `ReqCurrencyCount3` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyId3`,
ADD COLUMN                                   `ReqCurrencyId4` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyCount3`,
ADD COLUMN                                   `ReqCurrencyCount4` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyId4`,
ADD COLUMN                                   `QuestGiverPortraitText` text DEFAULT NULL AFTER `ReqCurrencyCount4`,
ADD COLUMN                                   `QuestGiverPortraitUnk` text DEFAULT NULL AFTER `QuestGiverPortraitText`,
ADD COLUMN                                   `QuestTurnInPortraitText` text DEFAULT NULL AFTER `QuestGiverPortraitUnk`,
ADD COLUMN                                   `QuestTurnInPortraitUnk` text DEFAULT NULL AFTER `QuestTurnInPortraitText`,
ADD COLUMN                                   `SoundAccept` int(11) unsigned NOT NULL DEFAULT '0' AFTER `QuestTurnInPortraitUnk`,
ADD COLUMN                                   `SoundTurnIn` int(11) unsigned NOT NULL DEFAULT '0' AFTER `SoundAccept`,
ADD COLUMN                                   `RequiredSpell` int(11) unsigned NOT NULL DEFAULT '0' AFTER `SoundTurnIn`;